export const demoTrainers = [
  {
    id: 1,
    name: "Abdur Rahim",
    position: "Web Developer",
    email: "rahim@example.com",
    fbId: "rahim.fb",
    webAddress: "https://rahim.dev",
    photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
  },
  {
    id: 2,
    name: "Karima Akter",
    position: "Graphic Designer",
    email: "karima@example.com",
    fbId: "karima.fb",
    webAddress: "https://karima.design",
    photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
  },
  {
    id: 3,
    name: "Hasan Ali",
    position: "Frontend Instructor",
    email: "hasan@example.com",
    fbId: "hasan.fb",
    webAddress: "https://hasan.dev",
    photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
  },
  {
    id: 4,
    name: "Sadia Rahman",
    position: "UI/UX Designer",
    email: "sadia@example.com",
    fbId: "sadia.fb",
    webAddress: "https://sadia.design",
    photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
  },
  {
    id: 5,
    name: "Imran Hossain",
    position: "Backend Developer",
    email: "imran@example.com",
    fbId: "imran.fb",
    webAddress: "https://imran.dev",
    photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
  },
];