
export const demoStudents = [
        {
            id: 1,
            name: "Rahim Uddin",
            fathersName: "Abdul Karim",
            mothersName: "Ayesha Begum",
            dateOfBirth: "2002-05-14",
            gender: "Male",
            phone: "01711111111",
            guardianPhone: "01899999999",
            email: "rahim.uddin@example.com",
            address: "Rangpur Sadar, Rangpur",
            paymentStatus: "Paid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 2,
            name: "Karima Akter",
            fathersName: "Jalal Uddin",
            mothersName: "Rokeya Begum",
            dateOfBirth: "2003-03-22",
            gender: "Female",
            phone: "01722222222",
            guardianPhone: "01877777777",
            email: "karima.akter@example.com",
            address: "Dinajpur Town, Dinajpur",
            paymentStatus: "Unpaid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 3,
            name: "Hasan Ali",
            fathersName: "Mofiz Uddin",
            mothersName: "Khadija Begum",
            dateOfBirth: "2001-09-10",
            gender: "Male",
            phone: "01733333333",
            guardianPhone: "01955555555",
            email: "hasan.ali@example.com",
            address: "Kurigram, Bangladesh",
            paymentStatus: "Paid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 4,
            name: "Sadia Rahman",
            fathersName: "Motiur Rahman",
            mothersName: "Salma Khatun",
            dateOfBirth: "2004-01-19",
            gender: "Female",
            phone: "01844444444",
            guardianPhone: "01788888888",
            email: "sadia.rahman@example.com",
            address: "Thakurgaon, Bangladesh",
            paymentStatus: "Unpaid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 5,
            name: "Imran Hossain",
            fathersName: "Nazrul Islam",
            mothersName: "Shahana Begum",
            dateOfBirth: "2002-07-07",
            gender: "Male",
            phone: "01955555555",
            guardianPhone: "01766666666",
            email: "imran.hossain@example.com",
            address: "Gaibandha, Bangladesh",
            paymentStatus: "Paid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 6,
            name: "Nusrat Jahan",
            fathersName: "Helal Uddin",
            mothersName: "Nazma Khatun",
            dateOfBirth: "2003-02-05",
            gender: "Female",
            phone: "01766666666",
            guardianPhone: "01888888888",
            email: "nusrat.jahan@example.com",
            address: "Lalmonirhat, Bangladesh",
            paymentStatus: "Paid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 7,
            name: "Sabbir Rahman",
            fathersName: "Kamrul Islam",
            mothersName: "Fatema Begum",
            dateOfBirth: "2001-11-27",
            gender: "Male",
            phone: "01977777777",
            guardianPhone: "01744444444",
            email: "sabbir.rahman@example.com",
            address: "Nilphamari, Bangladesh",
            paymentStatus: "Unpaid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 8,
            name: "Mim Akter",
            fathersName: "Latif Uddin",
            mothersName: "Rina Begum",
            dateOfBirth: "2004-08-13",
            gender: "Female",
            phone: "01888888888",
            guardianPhone: "01922222222",
            email: "mim.akter@example.com",
            address: "Panchagarh, Bangladesh",
            paymentStatus: "Paid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 9,
            name: "Arif Hossain",
            fathersName: "Rafique Uddin",
            mothersName: "Jahanara Begum",
            dateOfBirth: "2002-12-30",
            gender: "Male",
            phone: "01799999999",
            guardianPhone: "01833333333",
            email: "arif.hossain@example.com",
            address: "Bogura, Bangladesh",
            paymentStatus: "Unpaid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
        {
            id: 10,
            name: "Farzana Yasmin",
            fathersName: "Harun Or Rashid",
            mothersName: "Sufia Begum",
            dateOfBirth: "2003-06-25",
            gender: "Female",
            phone: "01988888888",
            guardianPhone: "01711111122",
            email: "farzana.yasmin@example.com",
            address: "Rangpur City, Bangladesh",
            paymentStatus: "Paid",
            photo: `https://i.pravatar.cc/150?img=${Math.floor(Math.random() * 70) + 1}`,
        },
    ];